site_name: ServiceSOAP Documentation Version 1.0
nav:
  - Home: index.md
  - API:
      - ServiceStruct: api/service_client.md
  - Client: 
    - ServiceClient: main/response_cliente.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python